services:
  - type: web
    name: affilimax
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: AFFILMAX_REQUIRE_LIVE
        value: "1"
      - key: AFFILMAX_BASE_URL
        value: "https://affilimax.onrender.com"
      - key: ADMIN_USER
        value: "admin"
      - key: ADMIN_PASSWORD
        sync: false
      - key: PARTNER_SECRET_KEY
        sync: false
      - key: STRIPE_DEFAULT_COUNTRY
        value: "FR"
      - key: STRIPE_DEFAULT_CURRENCY
        value: "eur"
